### ISSUE TITLE
US-11: As a supervised user, I want to be able to switch on or off the location detection functionality

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#11]

**Comment by refatK** [comment]
Since this  functionality already natively exists in Android, there's not really a reason to add a functionality on top of something that already exists natively in my opinion.

**Comment by ShawnGuerra-Bautista** [comment]
Agreed, this user story should be deleted.

**Comment by Landry333** [comment]
No need for this feature, because if a user doesn't want his / her location to be detected by the app, the user can just go to the application permission for location and disable it
