### ISSUE TITLE
Create an account and register username, a password, an email and  mobile phone number (User Story #47)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#142]
Expected steps:

Preconditions: The tester installed the Big Owl application on a smartphone.

1- Open the application for the first time
2- Click on the line "Don't have an account? Sign up"
3- Insert full name in the field "Name"
4- Insert an email in the field "Email"
5- Insert a password in the field "Password"
6- Insert a phone number in the field "Phone"
7- Click the "SIGN UP" button

Expected result: The tester will be signed in automatically, and see a profile with last name, full name, first name, phone number, and email on the homepage.

**Comment by anlepoly** [comment]
The feature is well implemented.
I hope that we further remind user that "all of the fields are required", which can improve our user experience.
