### ISSUE TITLE
Sign in (US #48)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#146]
Expected steps:

Preconditions: The tester installed the Big Owl application on a smartphone and has already created an account

1- Open the application
2- Make sure the app is connected to internet
3- If app is at registration page click on the "sign in at the bottom of page"
4- Enter email, password and click on "sign in " button

Expected result: The tester will be signed in, and see a profile with last name, full name, first name, phone number, and email on the homepage.

**Comment by anlepoly** [comment]
When users try to log in multiple times with wrong password, the app will block the users.
One more piece of information we need is that how the subject device will be unblocked (e.g., after a period of time ...)

**Comment by anlepoly** [comment]
The feature is well implemented, correct user info can be used to log in and wrong info will be prompt with error messages.
