### ISSUE TITLE
To add a user from phone number or from phone book contact (US #117)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#148]
Expected steps:

Preconditions: The tester installed the Big Owl application on a smartphone, has signed in and is at the home page

1- Click on the "add users" button and get redirected to an option page with 2 options: "invite from contact list" (option 1) and "invite by phone number" (option 2)
2- Option 1: Tester click on "invite from contact list" button and is redirected to a page listing all phone contacts in tester's phone with name and number. On the first time, tester will be prompted to give permission to access his phone book
    Option 2: Tester click on "invite by phone number" button and should be redirected to a page with an empty text field where to enter a phone number. Bellow the text field there should be a “search user” button.
3-  Option 1: Tester can either enter a name in the search bar to search for a name in the list and then click on a name or click at any time on a name in the list. After clicking on a name, if contact already registered to the app, then a toast/ pop up message tells tester that contact is already registered, asks to choose another contact and nothing else happens. If contact is not yet registered, then tester should be redirected to a page to send text sms. 
      Option 2: Tester enters a phone number in the text field and clicks on the “search user” button. If phone number is already registered to the app with a user, then a toast/ pop up message tells tester that contact is already registered, asks to choose another contact phone number and nothing else happens. If phone number is not yet registered, then tester should be redirected to a page to send text sms.

4- Both options: Tester has been redirected to a page to send text sms which contains a top message : "Contact:  **contactDetails**  is not yet registered to the application. Send her/him this invitation text sms". ContactDetails is the contact name followed by contact phone number. Bellow the top message, there should be an entry text field (Edit text) auto filled with the last 10 digit of the contact number. Tester should be able to edit that number on the entry field. Bellow the entry field, there should be an entry text field (Edit text) auto filled with the sms text message. Tester should be able to edit that message. Bellow the sms text message, there should be a button "send sms to invite".

5- Both options: Click on button "send sms to invite", the sms text message is sent. On the first time, tester will be prompted to give permission to phone to send regular text sms. Tester can not send message if autofill number and text sms message are replaced by nothing. An error message should pop up in that case if tester attemps to send

Expected result: The text sms will be sent as a regular text sms by phone, a toast/pop up message will apear and the tester will be redicted to a confirmation page containin a confirmation message at the top page and a "return to home page" button. On click on the "return to home page", tester will be redirected to home page.

**Comment by anlepoly** [comment]
1. A bug occurred when trying to add an existing user, refer to Issue #117
2. The SMS sending feature has not been implemented

**Comment by anlepoly** [comment]
We may send invitation by SMS+email or only email, because email notification is easy to implement
I suggest that developers spend some time to evaluate the difficulties of implementing SMS notification, if it's ready hard to go, we can go with email only
