### ISSUE TITLE
BUG-162: Mobile phone number should be a unique identifier when a user signs up

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#162]
### Related Issue(s): 
#47

### Relevant File(s):
SignUpPageActivity.java.
Not a relevant file, but constraints should be added to the Firestore Database.

### Describe the bug:
User should sign up with one phone number which uniquely belongs to that user. 
At the moment, the phone number in the database aren't unique.

### To Reproduce:
1. Sign up a new account using phone number X
2. Sign up a new account again using phone number X
3. Both registration should be possible

### Expected behavior
When creating an account with a phone number, this phone number should be unique for the account and should not be used for an another account.

### Screenshots/Video:
![Screenshot from 2021-01-21 21-33-34](https://user-images.githubusercontent.com/23643192/105438160-72414d80-5c30-11eb-818b-04ddf6a320fc.png)

![Screenshot from 2021-01-21 21-33-10](https://user-images.githubusercontent.com/23643192/105438138-681f4f00-5c30-11eb-83bc-d15232621c1f.png)

**Comment by refatK** [comment]
Since this isn't assigned to anyone, I'm going to move it to the backlog for now
