### ISSUE TITLE
AT-175: To send a request to supervise a user or to cancel a request to supervised that is still pending (related to US #73 and US #51)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#175]
Related to US #73 and US #51

Preconditions: The tester installed the Big Owl application on a smartphone, has signed in, has selected the add users button on the home page , has chosen a contact to send request and is now at the send request page

Expected steps

1- User is at the send request page which is having 2 messages. The first message tells tester that the chosen contact is already registered to the app

2- Option 1: If the user has not yet sent a request to the the chosen contact, then the second message will tell tester that there is no request created by him/her to supervise that contact. The page also contains a button labeled as "send a request to supervise this user"
    Option 2: If the user has already sent a request to the the chosen contact, then the second message will tell tester that he/she has a request to supervise that contact. The page also contains a button labeled as "You have a request already. Cancel request"
    Option 3: If the chosen contact had already accepted the request to supervise from the user, then the second message will tell the user he already has an accepted request from this contact. The page also contains a button labeled as "You are supervising this user". Then nothing else happens

3- Option 1: The user clicks on the button and a new notification with type : "request to supervise" is created in the database. Also the display will change: the second message will tell tester that he/she has a request to supervise that contact. The page also contains a button labeled as "You have a request already. Cancel request". Then nothing else happens

    Option 2: The user clicks on the button and the corresponding "request to supervise" notification will be deleted from the database. Also the display will change: the second message will tell tester that there is no request created by him/her to supervise that contact. The page also contains a button labeled as "send a request to supervise this user". Then nothing else happens

Expected result: A request is created or deleted in the data base and the display on the screen shows message and button corresponding either to user with no request to supervise (option 1), or a pending request to supervise (option 2)or an accepted request to supervise (option 3)

Postconditions: The user is at the send/cancel request to supervise action page and in the database, a new request has been created if the user sent a request or the corresponding request has been deleted if the user has canceled request

**Comment by anlepoly** [comment]
The feature is well implemented, checked
