### ISSUE TITLE
AT-186: To test: As a monitoring user, I want to be able to set time - location schedule with arrival time interval, departure time interval and location address for every user on my supervised users list (Related to US #30)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#186]
Related to US #30

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in as a user who has a group of supervised users under his supervision. The tester is at the home page

Expected steps

1. The tester will click on the set schedule button and will be redirected to the "Create New Schedule" screen
2. The "Create New Schedule" screen is a screen form that the tester will have to fill
3. On filling the form, the tester will have to enter :
      a)- A title; By clicking on the title field, and by using the phone keys pad that will pop to enter a title. Then, the tester will click on the finish / enter key
      b)- A group; By clicking on the "Select Group" field, the names of all the groups of users that the tester is supervising will pop on the screen and the user will select one by taping on it, then the name of that group will appear and replace the "Select Group" title on that field
      c)- User(s); After selecting a group of supervised users, the "Select Users(s)" field will become bold and when clicking on it, the tester will see the list of users of the group he / she selected in the previous step. The tester will then click on all users she / he want to include in the appointment / schedule. Then the tester will click on the "confirm" or will click on the "cancel" button at the bottom and will redirected to the "Create New Schedule" screen.  The cancel button will add nothing to the previous steps but the confirm button will add the list of selected users in the "Select Users(s)" field
     d)- Start date, Start time, End date, End time; The tester will enter the Start date, Start time, End date, End time of the schedule by using the "Start date", "Start time", "End date", "End time" fields in the same way he / she usually uses these kind of fields with his phone
     e)- location; By clicking on the "Select Location" field, the tester will be redirected to a search screen where she/he will enter an address and get  a list of suggestions. The tester will select one of them and will be return to the "Create new Schedule" screen and the selected address will be entered on the  "Select Location" space.

4. After entering all fields, the tester will click on the "Set Schedule" button then the schedule will be added to the database, a confirmation message will pop on the screen and the tester will be redirected to the home page. If there is any field not entered, a warning sign will instead appear beside that field when clicking on the "Set Schedule" button, and message "Please complete all necessary fields" will pop

Expected result: A schedule is created in the data base

Postconditions: The user/ tester is at the Home page and a new schedule has been created in the database

**Comment by anlepoly** [comment]
A non-supervisor user should not be allowed to create a schedule. When such a user intends to do so, the system should prompt a message like "You are not allowed to create a schedule" and will not let the user do so.
