### ISSUE TITLE
AT-188: To test: As a supervised user, I want to be able to see my time - location schedule(Related to US #31)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#188]
Related to US #31

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in as a supervised user for whom a schedule is supposed to have been created by one of his monitoring user / supervisor

Expected steps

1. From the home page, the tester will click on the "Supervised Group" button and will be redirected to the "List of supervised group" screen that will show all the groups of supervised users to which the tester belongs
2. The tester will click on one group and will be redirected to the "schedules" screen
3. The tester will click on the "schedule " button and :
      Case 1- if there are some schedules, the tester will be redirected to a screen with the list of all the names / titles of the schedules to which he / she has been associated by his group monitoring user / supervisor
      Case 2- If there are no schedules, a message "No schedule found" will pop with an "ok" button. The tester will have to click on the "ok" button to get back to the previous screen

4.  In case there are some schedules, the tester will choose and click on a schedule title and will be redirected to a screen with all the details of the schedule / appointment, i.e: group name, name of the group supervisor, appointment start time, end time. 

        Situation a)-  In case the schedules have not been accepted or rejected before, there will be a button "Accept" and a button "Reject" at the bottom of the screen.
                   Case 1- The tester clicks on accept button; A message stating the time the tester accepted the schedule will be added in the screen and the button "Accept" will disappear but the button "Reject" will remain at the screen bottom in case the tester would like to change his/ her choice
                   Case 2- The tester clicks on Reject button; A message stating the time the tester rejected the schedule will be added in the screen and the button "Reject" will disappear but the button "Accept" will remain at the screen bottom in case the tester would like to change her/ his choice

      At this step, whenever the tester will click on the stand alone "Accept" or "Reject" button, case 1 or case 2 situation be implemented, but the tester will have to wait at least 1 min before changing his / her choice otherwise a message will pop to inform the user about that and no choice will be change

     Situation b)-  In case the schedules have already been accepted or rejected, there will be a button either a button "Accept" if the schedule had been rejected before or  a  button "Reject" at the bottom of the screen if the schedule had been accepted before. And as in situation a), a message stating the time the tester rejected or accepted the schedule will be added in the screen

Expected result: The existing schedules were displayed properly with details: group name, name of the group supervisor, appointment start time, end time. If accepted or rejected previously, the last time of acceptance or rejection will be displayed

Postconditions: The user/ tester is at a page showing the schedule details to which she / he has been associated

**Comment by anlepoly** [comment]
We may create a wiki page or docs page to show some "hidden features".  For example, the meetings are sorted by date, but we'd better let users know it.
