### ISSUE TITLE
DOC-193: Release 2 documentation - Release Planning

### ISSUE THREAD

**Issue by ShawnGuerra-Bautista** [Landry333/Big-Owl#193]
### Description:
For each sprint, create a spring summary and write it in the documentation. This should include a table of issues closed/open/removed/Pushed/etc. Moreover, a retrospective, and the project velocity should be included.

**Comment by Landry333** [comment]
A similar issue already exist

**Comment by ShawnGuerra-Bautista** [comment]
Duplicate Issue: https://github.com/Landry333/Big-Owl/issues/190
