### ISSUE TITLE
AT-224: To test: As a user, I would like to view and edit my profile  (US-57)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#224]
Related to US #57

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in and is at the home page

Expected steps

  1. From the home page, the tester should be able to see his profile details: name, email and phone number
  2. The tester will click on the left most icon on the top screen navigation bar and will be given 4 options on a scrolling menu. 
  3. The tester will click on the edit profile option on the scrolling menu and will be redirected to a form on the edit profile page
  3. The tester will be able to edit profile details on the edit profile page and will click on confirm or cancel
  4. 
      a)- Clicking on the confirm button will confirm the changes made on the edit profile page and return the tester to home page
      b)- Clicking on cancel will ignore any input on the edit profile page and will return the tester to the home page with profile
            unchanged  

Expected result:  a)- If tester clicked on the button to confirm changes, then the profile on the home page show the new details entered by tester
                           b)- If tester clicked on the button to cancel changes, then the profile on the home page show the same details as before with no changes

Post-conditions: The user/ tester is at the home page

**Comment by anlepoly** [comment]
All the behaviours are as expected.
