### ISSUE TITLE
AT-225: To Test: As a supervised user, I would like to see the users who are monitoring me (US-56)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#225]
Related to US #56

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in and is at the home page

1. From the home page, the tester will click on the button "supervised group" and will be redirected to the "List of supervised group" screen which shows the list of all user who are monitoring the tester in a group

Expected result: The tester is at a screen that shows all his monitoring users

Post-conditions: The user/ tester is at the "List of supervised group" screen

**Comment by anlepoly** [comment]
There is a bug to be fixed for the small font text "by <supervisor name>"

**Comment by refatK** [comment]
@anlepoly Thanks for bringging that up, we have a issue related to this and will make sure to fix it:

#168
