### ISSUE TITLE
AT-226: To test: As a monitoring user, I would like to see the list of users I am monitoring(US-55)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#226]
Related to US #55

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in and is at the home page

  1. From the home page, the tester will click on the button "Monitoring group" and will be redirected to a screen which shows the list of all users who belongs to a group on which the tester is a supervisor or monitoring

Expected result: The tester is at a screen that shows all her / his supervised users

Post-conditions: The user/ tester is at the screen listing all users of the group he/ she is monitoring

**Comment by anlepoly** [comment]
This feature is woking as expected.
