### ISSUE TITLE
AT-227: As a user, I would like to access to the set schedule screen only if I am a supervisor of a group that is not empty (US-214)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#227]
Related to US #214

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in and is at the home page

   1. From the home page, the tester will click on the button "Monitoring group" 
   2. 
       a)- Case 1: 
              1. If tester is a supervisor of a group that has at least another user, then tester will be redirected to a screen which shows the list of all users who belongs to a group on which the tester is a supervisor or monitoring
              2. Tester will click on the "set schedule button" and will be redirected to the set schedule screen            

       b)- Case 2: 
             1. If tester is not a supervisor of a non empty group, then tester will get an alert pop up message that will warn him that he / she is not a monitor of a group and that will not allow him to go to another screen
             2. The tester will click on "ok" on the alert message to get back to the home page

Expected result: The tester is at a screen that set schedule screen if she / he is a supervisor of a non empty screen, otherwise the tester is back at the home screen

Post-conditions: The user/ tester is at the st schedule screen or at the home screen

**Comment by anlepoly** [comment]
When getting into the monitoring group page, the group title is overlapping with the "set schedule" button. This UI issue need to be fixed.
