### ISSUE TITLE
AT-266: To test: As a monitoring user, I would like to get confirmation screen of a new time-location schedule I have created for a supervised user (US-38)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#266]
Related to US #38

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in and has finished filling the form to create a schedule

On the "Create New Schedule" screen, the tester will click on the button "set schedule"

A form will pop up upon the "Create New Schedule" screen with all the information the tester has entered to create the schedule. There will be a "cancel" button and a "confirm" button at the bottom of the form.

Case 1
On clicking on the "confirm" button, the schedule will be created, a confirmation message will toast at the bottom screen and the tester will be redirected to the "monitoring group" screen

Case 2
On clicking on the "cancel" button, no schedule will be created and the tester will just be redirected to the "monitoring group" screen

Expected result: The schedule has been created if the tester clicks on the "confirm" button on the form, or nothing has been created if the tester clicks on the "cancel" button

Post-conditions: The tester is at the "monitoring group" screen after the schedule confirmation screen

**Comment by anlepoly** [comment]
Working as expected.
