### ISSUE TITLE
AT-267: To test: As a supervised user I would like to receive SMS alerts if my location can not be detected at the scheduled time for attendance check (US-15)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#267]
Related to US #15

Preconditions: The tester installed the Big Owl application on a smartphone, has created a schedule for a supervised user

The tester will make sure the supervised user location can not be detected at the schedule time (supervised user can be signed out or not connected to internet)

Expected result: 4 minutes after the start time the tester phone will send automatically a warning text SMS to the supervised user phone number

Post-conditions: The supervised user location is NOT_DETECTED and the app has triggered the tester phone to send a warning text SMS to the supervised user

**Comment by anlepoly** [comment]
Working as expected.
