### ISSUE TITLE
AT-269: To test: As a user, I would like to have a manual to teach how to user the app (US-213)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#269]
Related to US #213

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in and is at the home page

The tester will click on the 3 bars menu icon on the left of the top screen bar and then click on "wiki page manual" . The tester will be redirected to the wiki page manual document

Expected result: The tester has opened the app wiki page manual document

Post-conditions: The user/ tester is at the app  wiki page

**Comment by anlepoly** [comment]
Working as expected.
