### ISSUE TITLE
AT-270: To test: As a supervised user, I would like to respond to an attendance supervision request (US-52)

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#270]
Related to US #52

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in and is at the home page

1. The tester will click on the bell icon on the screen top bar menu and will see the list of notifications
2. The tester will click on a request to supervise notification and will be directed to a screen with details about the request
3. The tester will accept or reject request by choosing the accept or reject button

Case 1
    If tester accept, then he / she will be redirected to the notification list screen, the notification will be deleted and the tester 
will be added to the group of supervised users of the user who sent the request.

Case 2
    If tester rejects then he / she will be redirected to the notification list screen, the notification will be deleted and nothing else will happen

Expected result: The tester has accepted the schedule or the tester has rejected the schedule. The notifications has been deleted in both  cases.

Post-conditions: The tester has been added to a group if she/ he accepted the request. There is no more request to supervise notification.

**Comment by anlepoly** [comment]
Working as expected
