### ISSUE TITLE
BUG-284: Wrong confirmation message on screen when canceling a request to supervise

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#284]
### Related Issue(s): 
Related to #73 

### Relevant File(s):
SendingRequestToSuperviseActivity file

### Describe the bug:
When a monitoring user has just canceled a request he has sent, a message indicating that he /she still has a pending request is displayed

### To Reproduce:
1. Invite a registered user
2. Click on send request
3. Click on Cancel request
4. See the wrong message

### Expected behavior
Message should indicate that the monitoring user has no sent request

**Comment by ShawnGuerra-Bautista** [comment]
The PR related to this issue is already closed.
