### ISSUE TITLE
AT-286: To test: As a user, I would like to navigate the app using a universal navigation bar (US-165)

### ISSUE THREAD

**Issue by ggebran** [Landry333/Big-Owl#286]
### Linked User Story
#165

### Preconditions:
The user installed the Big Owl application on a smartphone and has logged in.

### Postconditions:
The user must still be still be logged in to the application unless they have logged out through the navigation bar.

### Test Steps:
1. User enters the login page
2. User fills in credential in login form
3. User clicks login button
4. User logs into the home page
5. User clicks on one of the navigation bar buttons

### Expected Result:
<List of expectations when the steps are completed.  Example below.>

- User is logged in into the system
- User is redirected to either pages on the navigation bar (Schedule, Profile, Notification, Home Page)

**Comment by anlepoly** [comment]
Working as expected.
