### ISSUE TITLE
AT-287: To test: As a user, I want to be notified whenever someone I sent a sms text invitation to registered to the application has created a new account (US-71)

### ISSUE THREAD

**Issue by ggebran** [Landry333/Big-Owl#287]
### Linked User Story
#71

### Preconditions:

1. The inviter is logged in
2. The invitee responded to the SMS by creating a new account

### Postconditions:

1. The inviter received a notification about the new account creation
2. The invitee has created a new account

### Test Steps:

1. User1 logs in
2. User1 navigates to the invitation by phone number page
3. User1 enters the desired phone number to be invited
4. User1 sends the SMS invitation to the entered phone number
5. User2 receives an SMS invitation from User1
6. User2 creates a new account
7. User1 receives a notification that User2 created a new account

### Expected Result:

- The inviter has received a notification for the new account creation
- The invitee has created a new account

### Alternative Steps:
<step by step explanation of the operation covering alternate flows. Example below.>

Path 1: The inviter sends an SMS invitation to the wrong phone number
1. User1 logs in
2. User1 navigates to invitation by SMS page
3. User1 enters the wrong phone number and sends the invitation
4. User2 does not receive any SMS invitation from User1
5. User1 may receive a notification for new account creation but for the wrong phone number

Path 2: The invitee does not create a new account
1. The invitee receives an SMS invitation
2. The invitee does not respond, and not not create a new account
3. The inviter does not receive a notification

**Comment by anlepoly** [comment]
Working as expected.
