### ISSUE TITLE
AT-290: As a user, I would like to be notified instantaneously whenever I have a new time- location schedule (US-32)

### ISSUE THREAD

**Issue by SeifElDerby** [Landry333/Big-Owl#290]
Related to US #32

Preconditions: The tester installed the Big Owl application on a smartphone, has logged in and is supervised by a user.

1- The tester will click on the bell icon on the screen top bar menu and will see the list of notifications
2- The tester will click on you have a new time- location schedule and  will be directed to a screen with details about the schedule

**Comment by ShawnGuerra-Bautista** [comment]
Duplicate of #299
