### ISSUE TITLE
AT-291: As a monitoring user/supervisor, I want to view the all the schedules that I created and relevant reports (US-25)

### ISSUE THREAD

**Issue by SeifElDerby** [Landry333/Big-Owl#291]
Related to US-25

### Preconditions:
 The tester installed the Big Owl application on a smartphone, has logged in and is at the home page

1- The tester will click on the calendar icon on the screen top bar menu and will see the list of schedule he created.
2- The tester will click on a schedule to access its details and its report data

### Expected Result:
the monitoring user/supervisor will see all the schedules he created and its relevant reports

### Postconditions:
the monitoring user/supervisor will monitor all the schedules he created

**Comment by ShawnGuerra-Bautista** [comment]
Duplicate of #300
