### ISSUE TITLE
AT-292: To test: As a supervised user, I would like to see my upcoming schedules (US-60)

### ISSUE THREAD

**Issue by ggebran** [Landry333/Big-Owl#292]
### Linked User Story
#60

### Preconditions:

1. The user must be logged in
2. The user must be supervised
3. The must have a schedule

### Postconditions:

1. The user is logged in
2. The user is being supervised
3. The user has an upcoming schedule

### Test Steps:
<step by step explanation of the operation. Example below.>

1. User logs in to the application with the credentials
2. User clicks on "supervising me"
3. User chooses a group and clicks on it
4. User clicks on "my scheduled" 
5. User chooses and clicks on one of the schedules 

### Expected Result:

- The application will display the corresponding schedule to the user

### Alternative Steps:
<step by step explanation of the operation covering alternate flows. Example below.>

Path 1: User does is not being supervised
1. User attempts to navigate to "supervising me" 
2. Application will display a pop up saying "No supervision group found!"

Path 2: User does not have a schedule

**Comment by anlepoly** [comment]
Working as expected.
