### ISSUE TITLE
AT-299: To test: As a user, I would like to be notified instantaneously whenever I have a new time- location schedule (US-32)

### ISSUE THREAD

**Issue by ggebran** [Landry333/Big-Owl#299]
### Linked User Story
#32

### Preconditions:
The tester installed the Big Owl application on a smartphone, has logged in and is supervised by a user.

### Postconditions:
<List of conditions that must be true after the execution of this operation>

### Test Steps:

1. The tester will click on the bell icon on the screen top bar menu and will see the list of notifications
2. The tester will click on you have a new time- location schedule and will be directed to a screen with details about the schedule

### Expected Result:
TBD

### Alternative Steps:
TBD

**Comment by anlepoly** [comment]
Working as expected.
