### ISSUE TITLE
US-4: As a user, I would like to see the list of users I am monitoring or the name of the monitoring user who is supervising me

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#4]

**Comment by ShawnGuerra-Bautista** [comment]
Split into #55 and #56

**Comment by Landry333** [comment]
It is possible to see that under supervision groups screen or group members screen

**Comment by ShawnGuerra-Bautista** [comment]
> It is possible to see that under supervision groups screen or group members screen

I marked it as deleted as this is a duplicated user story to #55 and #56.
