### ISSUE TITLE
Design system overview architecture

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#46]

**Comment by refatK** [comment]
In PR #74 for issue #58, me and @ShawnGuerra-Bautista looked into implementing a clean architecture to our application, and decided that Model-View-ViewModel Architecture (MVVM) is the way to go. We also started using it in that PR, and it should result it easier testing and better separation of concerns. It's also the architecture that [Android officially recommends using](https://developer.android.com/jetpack/guide#recommended-app-arch).
