### ISSUE TITLE
As a user, I would like to sign in and sign out from the application.

### ISSUE THREAD

**Issue by ShawnGuerra-Bautista** [Landry333/Big-Owl#48]
Details:

- To sign in to the application, the user would have to use their phone number, and password.

- To sign out from the application, the user would have to access a "quick menu" while signed on and click on the "sign out" option.

**Comment by darkheros12** [comment]
Firebase does not allow phone number and password creation. It requires an email. However, the user can create with phone number and OTP.

**Comment by Landry333** [comment]
The sign in can be done with email but the user mobile phone number should be required as a user information before opening an account
