### ISSUE TITLE
US-54: As a user, I would like to switch modes between monitoring and supervised mode

### ISSUE THREAD

**Issue by ShawnGuerra-Bautista** [Landry333/Big-Owl#54]
Details:
- This user story mostly affects the UI; each mode would have different views for the user. The back-end or database models are not affected by this feature.
- e.g. Activating monitoring mode would allow the user to have access to users that they are monitoring, and manage them.
- e.g. Activating supervised mode would allow the user to view the schedules that they have to respect

**Comment by Landry333** [comment]
Both options for monitoring user and supervised user are present on home page
