### ISSUE TITLE
BUG-95: Back button returns the user to a page that isn't suppose to be accessible

### ISSUE THREAD

**Issue by ShawnGuerra-Bautista** [Landry333/Big-Owl#95]
### Related Issue(s): 
#48

### Relevant File(s):
HomePageActivity.java, LoginPageActivity.java

### Describe the bug:
When logged out then pressing the back button, the user would be logged in again

### To Reproduce:
1. Log in successfully in the app
2. Log out of the app successfully by pressing the log out button on the app
3. Press the back button on the phone

### Expected behavior
When clicking the back button after logging out, the user should not be sent back to the home page. The app should be closed instead like any other app.

### Screenshots/Video:
https://user-images.githubusercontent.com/23643192/105436701-ac5d2000-5c2d-11eb-9475-8d7db898fa92.mp4

**Comment by refatK** [comment]
Not sure why this was closed. I don't see any PR that fixed it.
